/* ZippyScale — the vocabulary this cockpit is built on.
   Everything here came out of the discovery interview. Change it here, not inline.

   Generated by the agentic-cockpit skill. Safe to edit by hand afterwards. */
(function (root) {
  'use strict';

  var V = {
    /* who this is for */
    client: 'ZippyScale',
    item: 'engagement',              // what they sell, singular
    items: 'engagements',            // plural
    unique: true,            // one-of-one? decides the whole item model

    /* the ladder — in the client's own words */
    OPEN_STAGES: [
      "Enquiry",
      "Contacted",
      "Discovery booked",
      "Discovery done",
      "Pitched",
      "MOU sent",
      "Invoiced"
],
    CLOSED_STAGES: ['Won', 'Lost'],
    STAGE_HELP: {
      "Enquiry": "Came in from somewhere. Nobody has spoken to them yet.",
      "Contacted": "We have reached them. Working out whether there is a business here.",
      "Discovery booked": "A discovery call is in the diary.",
      "Discovery done": "We know what they do and where it hurts. Now build the pitch.",
      "Pitched": "They have seen what we would build. Waiting on their word.",
      "MOU sent": "Terms are with them. Revisions get counted on the record, not a new stage.",
      "Invoiced": "Signed in principle and the first invoice is raised. Money not in yet.",
      "Won": "Paid and starting. The engagement moves to the delivery board.",
      "Lost": "Not happening. The reason is on the record."
},

    /* what a salesperson marks against one item */
    MARKS: {
      "interested": "Interested",
      "quoted": "Quoted",
      "accepted": "Accepted",
      "declined": "Declined",
      "parked": "Parked for later"
},

    /* stages that describe a conversation about one specific item.
       Refused until something is in play — you cannot negotiate over nothing. */
    NEEDS_ITEM: [
      "Pitched",
      "MOU sent",
      "Invoiced"
],

    /* where enquiries arrive */
    SOURCES: {
      "referral": "Referral",
      "outbound": "Outbound \u2014 we went to them",
      "instagram": "Instagram",
      "whatsapp": "WhatsApp",
      "google": "Google",
      "meta": "Meta ad",
      "linkedin": "LinkedIn",
      "website": "Website",
      "event": "Event or meetup"
},

    /* the people */
    ROLES: {
      "owner": "Owner",
      "director": "Director",
      "account": "Account Manager",
      "builder": "Builder",
      "contractor": "Contractor"
},

    /* what gets forgotten today, and should not */
    SEED_AUTOMATIONS: [
      {
            "name": "MOU sent and unsigned for 7 days",
            "trigger": "mou_unsigned",
            "days": 7,
            "does": "Flags it and drafts the nudge. EGO's has been unsigned for months."
      },
      {
            "name": "A milestone has slipped",
            "trigger": "milestone_slipped",
            "does": "Alerts the owner the day a target date passes unmet."
      },
      {
            "name": "Invoice raised and unpaid past terms",
            "trigger": "invoice_overdue",
            "days": 15,
            "does": "Flags what is owed and by whom."
      },
      {
            "name": "Built but not pitched for 5 days",
            "trigger": "unpitched",
            "days": 5,
            "does": "Finished work earning nothing. Ingens sat like this."
      },
      {
            "name": "A live demo stopped responding",
            "trigger": "demo_down",
            "does": "Tells us before the client opens it."
      },
      {
            "name": "Handed over 30 days ago",
            "trigger": "checkin_due",
            "days": 30,
            "does": "Schedules the check-in that turns a build into a retainer."
      }
],

    /* The agent roster — one narrow worker per job nobody gets round to.
       `minutes` is your honest estimate of the human time one run replaces; it is what
       the time-saved figure multiplies, so an inflated guess becomes a lie on a
       dashboard. `client: true` means the output is seen by a customer, and that
       forces approval whatever mode the agent is in. */
    AGENTS: [
      {
            "id": "jarvis",
            "name": "Jarvis",
            "icon": "\u25c9",
            "trigger": "Every morning, and whenever you ask",
            "does": "Reads every engagement, every plan, every invoice and every live demo. Ranks what is going wrong and what is going well, then proposes which of the other agents should do what. Dispatches nothing without your yes.",
            "minutes": 30,
            "client": false
      },
      {
            "id": "chaser",
            "name": "The Chaser",
            "icon": "\u21bb",
            "trigger": "A build blocked on the client for more than 3 days",
            "does": "Finds every engagement waiting on their credentials, data, signature or decision. Names how many days it has been stuck and drafts the nudge.",
            "minutes": 10,
            "client": true
      },
      {
            "id": "closer",
            "name": "The Closer",
            "icon": "\u25b6",
            "trigger": "Work finished and not sent",
            "does": "Flags a build that is ready and unpitched, assembles the findings, the demo link and the credentials, and drafts the outreach.",
            "minutes": 25,
            "client": true
      },
      {
            "id": "watchman",
            "name": "The Watchman",
            "icon": "\u25ce",
            "trigger": "Every live demo, on a schedule",
            "does": "Checks each deployed client demo still loads and still passes its own checks. Reports before the client finds out.",
            "minutes": 15,
            "client": false
      },
      {
            "id": "collector",
            "name": "The Collector",
            "icon": "\u20b9",
            "trigger": "An invoice past its terms",
            "does": "Works out what is actually owed across every client, flags the overdue ones and drafts the reminder.",
            "minutes": 12,
            "client": true
      },
      {
            "id": "brief",
            "name": "Morning Brief",
            "icon": "\u2600",
            "trigger": "Every morning",
            "does": "One digest: what slipped, what is due this week, what is owed, what went quiet.",
            "minutes": 20,
            "client": false
      }
],

    /* The work that happens AFTER the money, when a different person does it.
       Empty means this business does not need a second board. */
    PRODUCTION_STAGES: [
      "Onboarding",
      "Demo",
      "Client data",
      "Testing",
      "Corrections",
      "Handover",
      "Running"
],
    PRODUCTION_HELP: {
      "Onboarding": "Their answers and their credentials. This is where builds stall.",
      "Demo": "The build itself, on their own data where we have it.",
      "Client data": "Their real records in, and checked.",
      "Testing": "With the client, two weeks.",
      "Corrections": "What testing threw up. One week.",
      "Handover": "Deployed, credentials handed over, they are trained.",
      "Running": "Live and ours to keep alive."
},
    PRODUCTION_OWNER: 'Builder'   // whose board this is
  };

  V.OPP_STAGES = V.OPEN_STAGES.concat(V.CLOSED_STAGES);

  if (typeof module !== 'undefined' && module.exports) module.exports = V;
  else root.VOCAB = V;
})(typeof self !== 'undefined' ? self : this);
