import type { CaseStudyMetadata, CaseStudySlug } from './types'

export const registry: Record<CaseStudySlug, CaseStudyMetadata> = {
  'homeopathic-clinic-patient-flow': {
    slug: 'homeopathic-clinic-patient-flow',
    title: 'Stop being your clinic\'s receptionist. Recover 25 hours a week in 28 days.',
    shortTitle: 'Homeopathic clinic: patient flow on autopilot',
    industry: 'Healthcare',
    primaryPain: 'Patient WhatsApp backlog',
    heroStatBefore: '30%',
    heroStatAfter: '<15%',
    heroStatLabel: 'no-show rate',
    seoTitle: 'Healthcare: How Homeopathic Clinics Automate Patient WhatsApp | ZippyScale Case Study',
    seoDescription: 'Patient WhatsApp backlog at midnight, 30% no-shows, zero refill reminders. 4-week sprint for Indian specialty clinics at ₹50L-3Cr revenue.',
    ogImage: '/case-studies/og/homeopathic-clinic-patient-flow.png',
    publishedAt: '2026-04-22',
    related: ['pharma-distributor-field-orders', 'coaching-institute-admission-to-enrollment'],
    hookVariants: {
      A: "How Dr. [Founder] Stopped Answering WhatsApp at Midnight",
      B: "The 30% No-Show Problem Every Indian Clinic Pretends Is Normal",
    },
  },
  'coaching-institute-admission-to-enrollment': {
    slug: 'coaching-institute-admission-to-enrollment',
    title: 'Stop losing leads in 5 counsellor WhatsApps. Convert 30% more in 28 days.',
    shortTitle: 'Coaching institute: admission to enrollment',
    industry: 'Education',
    primaryPain: 'Counsellor WhatsApp routing chaos',
    heroStatBefore: '5',
    heroStatAfter: '1',
    heroStatLabel: 'counsellor WhatsApps unified',
    seoTitle: 'Education: How Coaching Institutes Convert 30% More Admissions | ZippyScale Case Study',
    seoDescription: 'Five counsellor WhatsApps with no routing, demo no-shows, fee dunning misses. 4-week sprint for 480-1500 seat coaching institutes at ₹1Cr-8Cr revenue.',
    ogImage: '/case-studies/og/coaching-institute-admission-to-enrollment.png',
    publishedAt: '2026-04-22',
    related: ['homeopathic-clinic-patient-flow', 'professional-services-lead-to-cash'],
    hookVariants: {
      A: "How [Institute] Closed 30% More Admissions Without Hiring Counsellors",
      B: "The 5 Counsellor WhatsApp Problem Every Indian Coaching Institute Pretends Is Normal",
    },
  },
  'auto-parts-distribution-order-automation': {
    slug: 'auto-parts-distribution-order-automation',
    title: '₹16K/month replaces ₹40K/month of WhatsApp order entry.',
    shortTitle: 'Auto-parts distribution: dealer orders auto',
    industry: 'Manufacturing',
    primaryPain: 'Dealer WhatsApp + Tally double-entry',
    heroStatBefore: '12 hrs/wk',
    heroStatAfter: '0',
    heroStatLabel: 'manual order entry',
    seoTitle: 'Manufacturing: Auto-Parts Dealer Order Automation | ZippyScale Case Study',
    seoDescription: 'Sixty dealer WhatsApps daily, 12 hrs/week of Excel-to-Tally typing, 30% overdue collections. 4-week sprint for tyre and auto-parts distributors at ₹2-10Cr revenue.',
    ogImage: '/case-studies/og/auto-parts-distribution-order-automation.png',
    publishedAt: '2026-04-22',
    related: ['rice-mill-fmcg-production-distributor-automation', 'pharma-distributor-field-orders'],
    hookVariants: {
      A: "How [Distributor] Replaced ₹40K of Manpower with ₹16K of Stack",
      B: "The 60-Message Morning Every Auto-Parts Distributor Pretends Is Normal",
    },
  },
  'hvac-manufacturing-po-to-production-automation': {
    slug: 'hvac-manufacturing-po-to-production-automation',
    title: 'ERP NX cost ₹8L. Sales still runs on WhatsApp. Bridge it in 4 weeks.',
    shortTitle: 'HVAC manufacturing: ERP-to-sales bridge',
    industry: 'Manufacturing',
    primaryPain: 'ERP-sales-production disconnect',
    heroStatBefore: '2 days',
    heroStatAfter: '4 hrs',
    heroStatLabel: 'quote turnaround',
    seoTitle: 'Manufacturing: HVAC ERP-to-Sales Bridge | ZippyScale Case Study',
    seoDescription: '2-day quote turnaround, sales head\'s 800 chats locked on his phone, foreman won\'t log into NX. 4-week sprint for HVAC manufacturers at ₹5-25Cr revenue.',
    ogImage: '/case-studies/og/hvac-manufacturing-po-to-production-automation.png',
    publishedAt: '2026-04-22',
    related: ['auto-parts-distribution-order-automation', 'rice-mill-fmcg-production-distributor-automation'],
    hookVariants: {
      A: "How [Manufacturer] Bridged Their ₹8L ERP to Sales in 28 Days",
      B: "The 2-Day Quote Problem Every HVAC Manufacturer Pretends Is Normal",
    },
  },
  'rice-mill-fmcg-production-distributor-automation': {
    slug: 'rice-mill-fmcg-production-distributor-automation',
    title: 'The whiteboard stays. Everything else gets automated. 1-day month-end.',
    shortTitle: 'Rice mill / FMCG: plant + distributor auto',
    industry: 'Manufacturing',
    primaryPain: 'Whiteboard + WhatsApp + Tally chaos',
    heroStatBefore: '3 days',
    heroStatAfter: '1 day',
    heroStatLabel: 'month-end close',
    seoTitle: 'Manufacturing: Rice Mill + FMCG Plant Automation | ZippyScale Case Study',
    seoDescription: 'Whiteboard photos at 8 PM, 40-distributor WhatsApp group, 3-day month-end. 4-week sprint for rice mills, edible oil, and packaged food at ₹3-15Cr revenue.',
    ogImage: '/case-studies/og/rice-mill-fmcg-production-distributor-automation.png',
    publishedAt: '2026-04-22',
    related: ['auto-parts-distribution-order-automation', 'pharma-distributor-field-orders'],
    hookVariants: {
      A: "How [Mill] Cut Month-End from 3 Days to 1 Without Touching Tally",
      B: "The 8 PM Whiteboard Photo Every Rice Mill Owner Pretends Is Normal",
    },
  },
  'pharma-distributor-field-orders': {
    slug: 'pharma-distributor-field-orders',
    title: '5-day month-end close to 1-day. Without a new ERP.',
    shortTitle: 'Pharma distributor: MR field-to-cash',
    industry: 'Pharma',
    primaryPain: 'MR field orders + GSTR mismatches',
    heroStatBefore: '5 days',
    heroStatAfter: '1 day',
    heroStatLabel: 'month-end',
    seoTitle: 'Pharma: C&F Distributor MR Field Orders to GSTR Auto | ZippyScale Case Study',
    seoDescription: 'MR voice notes, 5-8% SKU error, 5-day month-end with GSTR mismatches, near-expiry write-offs. 4-week sprint for pharma C&F distributors at ₹3-10Cr revenue.',
    ogImage: '/case-studies/og/pharma-distributor-field-orders.png',
    publishedAt: '2026-04-22',
    related: ['homeopathic-clinic-patient-flow', 'auto-parts-distribution-order-automation'],
    hookVariants: {
      A: "How [Distributor] Closed Month-End in 1 Day Without Replacing Tally",
      B: "The 5-8% SKU Error Every Pharma Distributor Pretends Is Normal",
    },
  },
  'd2c-apparel-beauty-retention-automation': {
    slug: 'd2c-apparel-beauty-retention-automation',
    title: 'Bitespeed failed you. Here\'s the retention stack that doesn\'t.',
    shortTitle: 'D2C apparel + beauty: retention stack',
    industry: 'D2C',
    primaryPain: 'Founder DM bottleneck + cart abandons',
    heroStatBefore: '6 hrs',
    heroStatAfter: '5 mins',
    heroStatLabel: 'lead-to-first-touch',
    seoTitle: 'D2C: Apparel + Beauty Retention Stack After Bitespeed Failed | ZippyScale Case Study',
    seoDescription: 'Founder DM bottleneck, ₹2K cart abandons daily, post-iOS attribution broken. 4-week sprint for D2C founders at ₹50L-10Cr revenue who\'ve already failed at SaaS WABA tools.',
    ogImage: '/case-studies/og/d2c-apparel-beauty-retention-automation.png',
    publishedAt: '2026-04-22',
    related: ['hospitality-fnb-reservations-loyalty-stack', 'professional-services-lead-to-cash'],
    hookVariants: {
      A: "How [Brand] Stopped Founder DMs Without Losing Brand Voice",
      B: "Why Bitespeed, Wigzo, and Interakt Don\'t Stick (and What Does)",
    },
  },
  'professional-services-lead-to-cash': {
    slug: 'professional-services-lead-to-cash',
    title: 'Proposal in a day. Pipeline visible Monday morning. 4-week build.',
    shortTitle: 'Professional services: lead-to-cash',
    industry: 'Services',
    primaryPain: 'Senior partner bottleneck + DSO drift',
    heroStatBefore: '7 days',
    heroStatAfter: '1 day',
    heroStatLabel: 'proposal turnaround',
    seoTitle: 'Services: 10-20 Person Consulting Firm Lead-to-Cash Automation | ZippyScale Case Study',
    seoDescription: 'Senior partner is the bottleneck on every proposal, every invoice, every dunning call. 4-week sprint for consulting, tax, legal, branding, ESG firms at ₹1-5Cr revenue.',
    ogImage: '/case-studies/og/professional-services-lead-to-cash.png',
    publishedAt: '2026-04-22',
    related: ['d2c-apparel-beauty-retention-automation', 'corporate-travel-quotes-reconciliation'],
    hookVariants: {
      A: "How [Firm] Cut Proposal Turnaround from a Week to a Day",
      B: "The Senior-Partner-Is-the-Bottleneck Problem Every Advisory Firm Pretends Is Normal",
    },
  },
  'hospitality-fnb-reservations-loyalty-stack': {
    slug: 'hospitality-fnb-reservations-loyalty-stack',
    title: 'Stop losing Friday tables to Wednesday\'s missed Instagram DM.',
    shortTitle: 'Hospitality / F&B: reservations + loyalty',
    industry: 'Hospitality',
    primaryPain: 'IG + WA + Zomato fragmentation',
    heroStatBefore: '2 days',
    heroStatAfter: '90 mins',
    heroStatLabel: 'Zomato reconciliation',
    seoTitle: 'Hospitality: Cafe + Restaurant IG Reservations to Loyalty Stack | ZippyScale Case Study',
    seoDescription: '47 unread IG DMs, double-booked Friday tables, 2-day Zomato reconciliation, birthdays never captured. 4-week sprint for cafes and 2-5 outlet restaurant groups at ₹60L-8Cr revenue.',
    ogImage: '/case-studies/og/hospitality-fnb-reservations-loyalty-stack.png',
    publishedAt: '2026-04-22',
    related: ['d2c-apparel-beauty-retention-automation', 'corporate-travel-quotes-reconciliation'],
    hookVariants: {
      A: "How [Cafe] Cut Zomato Reconciliation from 2 Days to 90 Minutes",
      B: "The Friday Double-Booking Problem Every Cafe Owner Pretends Is Normal",
    },
  },
  'corporate-travel-quotes-reconciliation': {
    slug: 'corporate-travel-quotes-reconciliation',
    title: 'Quote in 4 hours. P&L on day 2, not day 8.',
    shortTitle: 'Corporate travel: quotes + reconciliation',
    industry: 'Travel',
    primaryPain: 'RFQ chaos + vendor reconciliation drift',
    heroStatBefore: '36 hrs',
    heroStatAfter: '4 hrs',
    heroStatLabel: 'quote turnaround',
    seoTitle: 'Travel: Corporate Travel Agency Quote-to-P&L Automation | ZippyScale Case Study',
    seoDescription: 'Two agents quoting same RFQ, 36-hour quote turnaround, 8-day P&L lag, vendor rebates expire unclaimed. 4-week sprint for corporate travel agencies at ₹1.5-10Cr revenue.',
    ogImage: '/case-studies/og/corporate-travel-quotes-reconciliation.png',
    publishedAt: '2026-04-22',
    related: ['professional-services-lead-to-cash', 'hospitality-fnb-reservations-loyalty-stack'],
    hookVariants: {
      A: "How [Agency] Cut Quote Turnaround from 36 Hours to 4",
      B: "The Two-Agents-Quote-Same-RFQ Problem Every Travel Agency Pretends Is Normal",
    },
  },
}

export function getMetadata(slug: string): CaseStudyMetadata | undefined {
  if (slug in registry) return registry[slug as CaseStudySlug]
  return undefined
}
